### ISSUE TITLE
pywal

### ISSUE THREAD

**Issue by zzzeyez** [fehawen/terco#1]
hey, i really like your work with color palettes and have converted your schemes to be used with `pywal`.  they are in the directory i linked below with the suffix `terco-`.  i also have linked the tool i created to convert your palettes

https://github.com/zzzeyez/dots/tree/master/wal/colorschemes/colorlovers

https://github.com/zzzeyez/bin/blob/master/x-to-json

**Comment by fehawen** [comment]
Hey,

Thank you, glad to hear you like it.

Using predefined palettes with `pywal` is really neat, and not something I've considered or utilized myself before. I've only ever used it with images.

The x-to-json tool is interesting; I might use it to convert palettes myself at some point.

Also, if you have any preferred colorschemes you'd like to share, feel free to add them to [pap](https://github.com/fehawen/pap) with a PR. I wouldn't mind if there were more themes available out of the box.
